### PR TITLE
webrender: implement xw-color-values. Fixes #129.

### LINKED ISSUE #129: Webrender colors support.
Some themes works fine with `webrender`. But some doesn't. For example, `solarized-dark` doesn't work:
Снимок экрана от 2021-01-24 02-28-45

### PR DESCRIPTION
**Pull request by harryfei**
Fixes #129

### CODE REVIEW

File: rust_src/src/wrterm.rs [hunk 1]
```diff
@@ -377,8 +378,18 @@ pub fn x_display_grayscale_p(_terminal: LispObject) -> bool {
...
 /// Internal function called by `color-values', which see.
 #[lisp_fn(min = "1")]
-pub fn xw_color_values(_color: LispObject, _frame: Option<LispFrameRef>) -> LispObject {
-    Qnil
+pub fn xw_color_values(color: LispObject, _frame: Option<LispFrameRef>) -> LispObject {
+    let color_str = format!("{}", color.force_string());
+    match lookup_color_by_name_or_hex(&color_str) {
+        Some(c) => unsafe {
+            list3i(
+                (c.r * 65535.0) as i64,
```
Comment (DavidDeSimone) [inline rust_src/src/wrterm.rs:386]: would this be cleaner as just u16::MAX?
