### PR TITLE
webrender: render composite glyph.

### LINKED ISSUE #322: Webrender bleeds symbols/fonts for org notes
Org notes appear with previous symbols bleeding into each other. This is more noticeable with more complicated org notes (with combinations of TODOs, lists, in line images, code blocks).

See screen shot for example.
webrender_org_mode

To reproduce: 
Scroll up and down on the following:
```
#+TITLE: Example Org Note

* This is a top line item
** What is Lorem Ipsum?

/"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."/

** What is this other thing?
*** Action items
#+name: plantuml_example
#+begin_src plantuml :file activity.png :exports results
@startuml

partition Conductor {
  (*) --> "Climbs on Platform"
  --> === S1 ===
  --> Bows
}

partition Audience #LightSkyBlue {
  === S1 === --> Applauds
}

partition Conductor {
  Bows --> === S2 ===
  --> WavesArmes
  Applauds --> === S2 ===
}

partition Orchestra #CCCCEE {
  WavesArmes --> Introduction
  --> "Play music       "
}

@enduml

#+end_src

#+begin_src python :results output
for _ in range(0, 20):
    print("Hello world")

#+end_src

#+RESULTS:
#+begin_example
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
#+end_example

+ This is a point
  - This is a point
+ This is a point
+ This is a point

- other points

*** All the actions [1/11]
**** TODO this item
**** TODO this item
**** TODO this item
***** TODO this item
***** WAIT this item
***** TODO this item
**** TODO this item
**** STRT this item
**** IDEA this item
**** TODO this item
**** TODO this item
**** TODO this item
**** TODO this item
**** DONE this item

```

### PR DESCRIPTION
**Pull request by harryfei**
fixes #322

### CODE REVIEW

File: rust_src/crates/webrender/src/draw_canvas.rs [hunk 1]
```diff
@@ -269,6 +270,114 @@ impl DrawCanvas {
...
+
+            let face = s.face;
+
+            let gc = s.gc;
+
+            let visible_height = if unsafe { (*s.row).mode_line_p() } {
+                unsafe { (*s.row).height }
+            } else {
+                unsafe { (*s.row).visible_height }
+            };
```
Comment (brotzeit) [inline rust_src/crates/webrender/src/draw_canvas.rs:332]: Maybe wrap the whole let binding into one `unsafe` block ?

**Review by brotzeit — APPROVED** [review]
